### ISSUE TITLE
Pretrain process

### ISSUE THREAD

**Issue by pvcastro** [jarib/spacy-nb#2]
Hi there! 

I'm doing the same thing for Portuguese, but you seem to have a better performance than I'm having, regarding the pretrain process. 

My pretrain is also taking about 2.5 hours per iteration (as you stated [here](https://github.com/explosion/spaCy/issues/3082#issuecomment-450731123)), but my corpus is based on a Wikipedia dump, which has around 230 million tokens. 

Did you eventually went for a pretrained model that ran for more iterations? Instead of that random 7th-iteration one you picked?

Thanks!

**Comment by jarib** [comment]
Hi! 

Unfortunately I haven't had time to run more pretraining, so I have nothing new to report. If I'm going to spend computing power on more iterations I think I would like to prepare the full Norwegian News Corpus (not just the subset I used in that comment), or find another corpus. I haven't tried pretraining on Norwegian Wikipedia.
